### ISSUE TITLE
这个怎么引入自定义词典?

### ISSUE THREAD

**Issue by kwaziidev** [yanyiwu/ngx_http_cppjieba_module#1]
nginx配置文件怎么引入 user.dict.utf8 这个文件?

**Comment by yanyiwu** [comment]
@gloomyzerg  不要意思，让客官您久等了。刚洗完澡，新提交了一个 commit 把自定义词典给支持起来了。
使用方法也在 README.md 里面已更新。

**Comment by kwaziidev** [comment]
看到了 谢谢  我们已经用于生产环境了  目前来看挺好
